# Generated by Django 5.0.7 on 2025-11-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_driver',
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='pool_app.vehicle'),
        ),
    ]
