# Generated by Django 5.0.7 on 2025-11-16 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pool_app', '0002_alter_booking_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='assigned_vehicle',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='distance_travelled',
        ),
        migrations.AddField(
            model_name='tripreport',
            name='end_odometer',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripreport',
            name='start_odometer',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pool_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool_app.booking'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='fuel_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='pool_app.driver'),
        ),
    ]
