# Generated by Django 5.0.7 on 2025-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0002_alter_driver_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Booked', 'Booked'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=20),
        ),
    ]
