# Generated by Django 5.0.7 on 2025-11-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0003_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Keeps driver name for history when vehicle is Out of Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previously_assigned_vehicles', to='pool_app.driver'),
        ),
    ]
