# Generated by Django 5.0.7 on 2025-12-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0004_vehicle_last_assigned_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripreport',
            options={'ordering': ['-completed_at']},
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='fuel_used',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='start_odometer',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Shows previous driver when vehicle is Out of Service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previously_assigned_vehicles', to='pool_app.driver'),
        ),
    ]
