# Generated by Django 5.0.7 on 2025-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0005_alter_tripreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='completed_at',
            field=models.DateTimeField(),
        ),
    ]
