# Generated by Django 5.0.7 on 2025-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0006_alter_tripreport_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
        ),
    ]
