# Generated by Django 5.0.7 on 2025-12-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0007_tripreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_avatar.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
