# Generated by Django 5.0.7 on 2025-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_app', '0012_driver_photo_vehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
